# -*- coding: utf-8 -*-
"""miniproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0zdupVc-_9VNe3r2lpUC2s1O6vNhGMc
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('/content/uber.csv')
df.head()

df.tail()

df.shape

df.columns

df.info()

df["pickup_datetime"] = pd.to_datetime(df["pickup_datetime"])

df.info()

df.describe()

df.isnull().sum()

df.dropna(inplace=True)

df.isnull().sum()

df.duplicated().sum()

df.drop(["Unnamed: 0", "key"], axis=1, inplace=True)

df.head()

df["year"] = df["pickup_datetime"].dt.year

df["month"] = df["pickup_datetime"].dt.month

df["day"] = df["pickup_datetime"].dt.day

df["hour"] = df["pickup_datetime"].dt.hour

df["weekday"] = df["pickup_datetime"].dt.weekday

df.head()

df.drop("pickup_datetime", axis=1, inplace=True)

df.columns

df.describe()

df = df[df["fare_amount"] > 0]

df = df[df["passenger_count"] > 0]

df = df[df["passenger_count"] <= 6]

df.describe()

plt.hist(df["fare_amount"], bins=40)
plt.title("Distribution of Fare Amount")
plt.xlabel("Fare Amount")
plt.ylabel("Frequency")
plt.show()

plt.boxplot(df["fare_amount"])
plt.title("Boxplot of Fare Amount")
plt.show()

df = df[df["fare_amount"] <= 200]

plt.boxplot(df["fare_amount"])
plt.title("Boxplot of Fare Amount")
plt.show()

import seaborn as sns
plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

X = df.drop("fare_amount", axis=1)
y = df["fare_amount"]

print(X.head())

print(y.head())

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

result = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

result.head(10)

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
reg=RandomForestRegressor()
n_estimators = [25,50,75,100,125,150,175,200]
criterion = ['squared_error']
max_depth=[3,5,10]
parameters={'n_estimators':n_estimators,'criterion':criterion,'max_depth':max_depth}
rf_model = GridSearchCV(reg,parameters)

rf_model.fit(X_train, y_train)

from sklearn.metrics import r2_score, mean_squared_error
import numpy as np
rf_pred = rf_model.predict(X_test)
print("R² Score :", r2_score(y_test, rf_pred))
print("MSE      :", mean_squared_error(y_test, rf_pred))